### ISSUE TITLE
Scannig library for the first time problem.

### ISSUE THREAD

**Issue by plutonick** [beville/ComicStreamer#16]
Scan status: SCANNING
Monitor: sorting recursive file list

I only entered my 'general' comics folder, which includes many subdirectories. Would this be responsible for the error?

Btw, total comics are no more than 5000

**Comment by velnias** [comment]
First I'd like to say thanks.  This is exactly what I was looking for to complement Mylar and my iPad using Chunky Comic Reader.

Having same issue.  Removed everything, even APPDATA files.  Reinstalled everything, even Python.  When starting, I notice in the following error in command window:

```
2016-01-25 06:49:32,920 - INFO - Stream server running on port 32500...
2016-01-25 06:49:33,127 - INFO - Monitor: Beginning file scan...
2016-01-25 06:49:33,486 - WARNING - Cannot run bonjour server!  Maybe some packages need to be installed?
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\ComicStreamer\comicstreamerlib\monitor.py", line 81, in mainLoop
    self.dofullScan(self.paths)
  File "c:\ComicStreamer\comicstreamerlib\monitor.py", line 481, in dofullScan
    filelist = sorted(filelist, key=os.path.getmtime)
  File "C:\Python27\lib\genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
WindowsError: [Error 3] The system cannot find the path specified: u'c:\\comics\
\Teenage Mutant Ninja Turtles Color Classics (2012)\\Teenage Mutant Ninja Turtle
s Color Classics Micro Series 002- Michaelangelo (2012) (digital-TheGroup)\\Teen
age Mutant Ninja Turtles Color Classics Micro Series 002- Michaelangelo (2012) (
digital-TheGroup).cbr'
```

ComicStreamer still loads, but the database never gets built.  Bonjour is installed and running.  
Troubleshooting steps:
1. In CS Config, cleared my comics folder and saved.
2. Rebuild database from Control.
3. Stopped CS.
4. Restarted CS.
5. Added comic folders back to Config. and restarted CS.

My comics folder is 973 Files, 685 Folders at around ~32GB.
Appreciate any guidance.

**Comment by wyldphyre** [comment]
So this is just a guess, but I notice that the path to the .cbr file in question is about 273 characters long. Windows (or parts of it at least) have a maximum file path length of 255 (or 250, I forget exactly).

It's a bit of a long shot, but maybe try shortening the file path and see if that helps.
