### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by smyther** [beville/ComicStreamer#20]
Get this error when running ./comicstreamer

Afaik i have all deps installed - i'm running Ubuntu 12.04.5 LTS

Thanks

**Comment by smyther** [comment]
Full traceback:

Traceback (most recent call last):
  File "comicstreamer.py", line 5, in <module>
    main()
  File "/mydir/ComicStreamer/comicstreamerlib/main.py", line 121, in main
    Launcher().go()
  File "/mydir/ComicStreamer/comicstreamerlib/main.py", line 72, in go
    config = ComicStreamerConfig()
  File "/mydir/ComicStreamer/comicstreamerlib/config.py", line 72, in **init**
    tmp = ConfigObj(self.filename, configspec=self.configspec, encoding=self.encoding)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1230, in **init**
    self._load(infile, configspec)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1327, in _load
    self._handle_configspec(configspec)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1919, in _handle_configspec
    _inspec=True)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1230, in __init__
    self._load(infile, configspec)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1290, in _load
    infile = self._handle_bom(infile)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1445, in _handle_bom
    if not line.startswith(BOM):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

**Comment by davide-romanini** [comment]
Check the settings file in ~/.ComicStreamer/settings. It seems not correctly utf-8 encoded. Eventually try deleting/moving it, comicstreamer will try to recreate it in that case.

**Comment by smyther** [comment]
Found the issue. Somehow i managed to install an older version of configobj..

Sorry about that!

**Comment by rlivre** [comment]
I Tried to install ComicStreamer yesterday and received the same error. Smyther's info about the old version of configobj made me think and so:

In my Linux Mint 17.2, the package confobj.py is installed by the system and it is stuck in version 4.7.2. I had to download version 5.0.6 from the pypi.python site and put it in /opt/comicstreamer/libs/
to make it work.
