### ISSUE TITLE
Parse strip time error

### ISSUE THREAD

**Issue by blindpet** [beville/ComicStreamer#30]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/comicstreamer/comicstreamerlib/monitor.py", line 81, in mainLoop
    self.dofullScan(self.paths)
  File "/opt/comicstreamer/comicstreamerlib/monitor.py", line 524, in dofullScan
    md = self.getComicMetadata( filename )
  File "/opt/comicstreamer/comicstreamerlib/monitor.py", line 169, in getComicMetadata
    if ca.seemsToBeAComicArchive():
  File "/opt/comicstreamer/libs/comictaggerlib/comicarchive.py", line 629, in seemsToBeAComicArchive
    ( self.getNumberOfPages() > 0)
  File "/opt/comicstreamer/libs/comictaggerlib/comicarchive.py", line 786, in getNumberOfPages
    self.page_count = len( self.getPageNameList( ) )
  File "/opt/comicstreamer/libs/comictaggerlib/comicarchive.py", line 762, in getPageNameList
    files = self.archiver.getArchiveFilenameList()
  File "/opt/comicstreamer/libs/comictaggerlib/comicarchive.py", line 396, in getArchiveFilenameList
    for item in rarc.infolist():
  File "/opt/comicstreamer/libs/comictaggerlib/UnRAR2/__init__.py", line 127, in infolist
    return list(self.infoiter())
  File "/opt/comicstreamer/libs/comictaggerlib/UnRAR2/__init__.py", line 122, in infoiter
    for params in RarFileImplementation.infoiter(self):
  File "/opt/comicstreamer/libs/comictaggerlib/UnRAR2/unix.py", line 171, in infoiter
    data['datetime'] = time.strptime(fields[2]+" "+fields[3], '%d-%m-%y %H:%M')
  File "/usr/lib/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2011-07-13 18:06' does not match format '%d-%m-%y %H:%M'
```

**Comment by blindpet** [comment]
Installing unrar and restarting comicstreamer seemed to do the trick

**Comment by socratesJ80** [comment]
I'm having this same problem. Did you do anything else other than installing unrar?

**Comment by blindpet** [comment]
@socratesJ80 I believe I symlinked it to the comicstreamer /lib/unrar

ln -s /opt/comicstreamer/lib/unrar /usr/bin/unrar

[Build the latest unrar](http://www.htpcguides.com/install-sabnzbd-ubuntu/) (works on any Debian/ubuntu system with any architecture)

**Comment by chromerobv** [comment]
having same issue. installed lated unrar and still same thing.

**Comment by davide-romanini** [comment]
You should try my fork https://github.com/davide-romanini/ComicStreamer/, on linux just:
- clone the repo
- pip install -r requirements.txt
- paver libunrar
  This assumes you have build tools (c/c++ compilers and tools) installed and working properly. Perhaps you'll need some more dev headers for pillow (image handling). Another option is to try the Dockerfile suggested in issue #28..

**Comment by Nataschrist** [comment]
Thank you very much, if you want feedback I'll be happy to comply,but until I have something useful out their myself, I'm not going to critique anyone else's genius. Thank you sir.
