### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by ghost** [beville/ComicStreamer#33]
Due to not being able to scan the local network i unplugged it while in the config page... eventhough it loades it cannot save because the network shares are not available  but if i enable the network it cannot save because it hangs...  see other issue. so when the paths of the comics is not found it could be nice to save... maybe give a warning and present the user to save anyway instead of the error also when the server needs restarting why does it not ask the user if it want to restart?

**Comment by ghost** [comment]
ow also broken are the html5 reader and the library section is empty while there are 1362 comics present... 

i wish i hadn't reinstalled osx from 10.11.0 to 10.11.2...  
1.11.0 was working :/.  

The work around for scanning from a network share with the broken version is to 

unmount network share
disable network
use extrnal usb drive with volume name same as share
(see /Volumes/ folder)
scan locally. 
stop comicserver
Disconnect drive 
connect network 
mount share
and start conicsteamer

**Comment by ghost** [comment]
Forgot to mention, i have no internet. That could be the problem, is it trying to update/download/check something online? maybe not your code but the library you are using? but I have no way to check it out if it works normal "with"... or a debug log... The scanning works perfectly when there is no wifi or ethernet connection... (probably generalise that to no network connection) en the reading works perfectly with a network connection. Still pain in the ass when adding new comics to disconnect all network connections and rescan... I dislike manual labor... (still like to use my hand tough, maybe the term is "extra" manual labor)... So it is only half broken. I guess... but is this project still "a-live?" Anybody out there? Or do I talk to the "incredible interwoven machine" again :-) Happens sometime...  ow btw... PDF support would be nice! there is probably a library who can give you a jpg page from a pdf... which comicserver could use... that would be awesome!!!

**Comment by ghost** [comment]
Ow and pleeaaaase help! Or do something to kickstart this project!

**Comment by ghost** [comment]
Don't make awesome shit and quit!

**Comment by davide-romanini** [comment]
It's a bit daunting having real work (well, at least a bit..) on a fork and having the issue tracker on the (dead) original repo. :-D
Maybe we should reboot the project...

**Comment by Nataschrist** [comment]
I had no intention of wasting your time. I sincerely apologize if that's what you're inferring.

**Comment by ghost** [comment]
I vote for reboot... we should ask github (or beville) to make i think you
(d.r.) owner...

if somesome will help with sqlalchemy to get mysql running (the delete is
not working)

i have a new gui (almost finished, could use some css advice though)
i have a cache (speeds up things alot)

and lots of bug fixes in the pipeline..

we probably could release a new version which is a lot faster.

**Comment by ghost** [comment]
Prototype: 

Broken cache, mysql not working... new gui direction will post a working forks when I am beter and online again... (not using phone access to server & code)

https://dl.dropboxusercontent.com/u/12474226/ToiletStreamer-0.9.4.dmg

ow btw... the whole toilet is a joke for my friend who spends way to much time there...

Crap Source
https://dl.dropboxusercontent.com/u/12474226/ToiletStreamerOld.zip

Example page (screenshots):

http://???/Toiletstreamer/

Anyway there is a database copy.py which contains the mysql code, to enable rename it to database.py and in server.py change

```
    self.dm = DataManager()
```

into 
        self.dm = DataManager(config)

I can not get the delete to function... also it seems that no comics are ever deleted...

Cache is very old code, I used this to check if it really speeded things up... hacked in...

Gui, I have to adjust font sizes... still not sure how things work when scaling...

So this is my prototype, I am up for a reboot, if somebody fixes the mysql code, somebody helps with those #$% css stuff...

will post normal github forks when online (dropbox is just in case i am not getting better, internet goes offline, or... or I go blind, or... start my own evil-comic empire _har_ _har_

**Comment by LucidusAtra** [comment]
Hey Tristan79, are you ever going to prepare a Windows release for ToiletStreamer? I don't know nearly enough about coding to compile the source code myself (I don't even know enough to know if your new code COULD be compiled for Windows...) but I use ComicStreamer very frequently, and would love to see what you've added. It's a great program, but it could use a GUI update and some new features (like multi-user reading progress tracking).

**Comment by ghost** [comment]
You do not have to compile it... 

install python 2.7 (not 3.x) for windows 

download the master zip file https://github.com/Tristan79/ComicStreamer/archive/master.zip or clone with github... remove the line 18 of requirements.txt (pybonjour==1.1.1) since you have to install that manually and you probably will not need it...

https://github.com/Tristan79/ComicStreamer/blob/master/requirements.txt#L18

run inside the (unzipped) ComicStreamer folder 

`pip install requirements.txt`

tot install the missing python packages...

and for the pdf support you need http://mupdf.com/downloads/  mutool.exe installed and in your path 

and change the file `comicapi/comicarchive.py `

the lines (615 and 655)
https://github.com/Tristan79/ComicStreamer/blob/master/comicapi/comicarchive.py#L655
https://github.com/Tristan79/ComicStreamer/blob/master/comicapi/comicarchive.py#L615

such that `'mudraw'` is `'mutool draw'`

and then run: `python comicstreamer`

that should work i hope, I do not have windows :-) 

And the web is still not finished :-) but i rather fix the mysql and the caching part... both speeded things up a lot  :-) but i got sick, before i could finish it, my own server is down for month cuz there are still some files it crashes on... (like 1 in every 10.000 :-) maybe februari i am going to spent some time on this :-)

Post here if you experiencing any troubles!

**Comment by LucidusAtra** [comment]
Okay, so I'm in an elevated cmd prompt. I navigate to the unzipped folder. I've changed line 18 of requirements.txt. And then, I try to do a pip install and get the message:

"Collecting requirements.txt
Could not find a version that satisfies the requirement requirements.txt (from versions: ) 
No matching distribution found for requirements.txt"

I also tried `python -m pip install <the full path of requirements.txt>`
I get a different message;

"Invalid requirement: 'C:\Users\Zack\Desktop\ComicStreamer-master\requirements.txt'
It looks like a path. Does it exist ?"

**Comment by ghost** [comment]
ok i think its

pip install -r requirements.txt

*and if that does not work try*

pip install python-dateutil
pip install argh
pip install backports.ssl-match-hostname
pip install certifi
pip install configobj
pip install natsort
pip install pathtools
pip install Pillow
pip install PyPDF2
pip install python-dateutil
pip install PyYAML
pip install six
pip install SQLAlchemy
pip install tornado
pip install unrar
pip install watchdog
pip install paver
pip install pylzma

python-dateutil==2.4.2

**Comment by LucidusAtra** [comment]
Wow, thanks for replying so quickly! 

So the command was `python -m pip install -r requirements.txt`

You were right, the `-r` flag was required to specify to pip that I wanted to install multiple packages from a requirements file. So it went through the installation and everything seemed to be going fine until the very end, when I got:

"error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27

Command "C:\Python27\python.exe -u -c "import setuptools, tokenize;file='c:\users\zack\appdata\local\temp\pip-build-hf1qfy\pylzma\setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record c:\users\zack\appdata\local\temp\pip-omvymb-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\zack\appdata\local\temp\pip-build-hf1qfy\pylzma"

Looks like I'm on the right track. `python comicstreamer` gets me this;

"C:\Users\Zack\Desktop\ComicStreamer-master>python comicstreamer
Traceback (most recent call last):
File "comicstreamer", line 6, in 
from comicstreamerlib.main import main
File "C:\Users\Zack\Desktop\ComicStreamer-master\comicstreamerlib\main.py", line 15, in 
from server import APIServer
File "C:\Users\Zack\Desktop\ComicStreamer-master\comicstreamerlib\server.py", line 41, in 
from comicapi.comicarchive import *
File "C:\Users\Zack\Desktop\ComicStreamer-master\comicapi\comicarchive.py", line 12, in 
from unrar import rarfile
File "C:\Python27\lib\site-packages\unrar\rarfile.py", line 26, in 
from unrar import unrarlib
File "C:\Python27\lib\site-packages\unrar\unrarlib.py", line 45, in 
unrarlib = ctypes.WinDLL(lib_path)
File "C:\Python27\lib\ctypes_init_.py", line 362, in init
self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found"

So it won't run quite yet. But we're close, I think.

**Comment by LucidusAtra** [comment]
I followed that link and installed the C++ compiler for python, then ran the pip install again and got Plyzma to install! 

Now, `python comicstreamer` gets me this:

"Traceback (most recent call last):
  File "comicstreamer", line 6, in <module>
    from comicstreamerlib.main import main
  File "C:\Users\Zack\Desktop\ComicStreamer-master\comicstreamerlib\main.py", line 15, in <module>
    from server import APIServer
  File "C:\Users\Zack\Desktop\ComicStreamer-master\comicstreamerlib\server.py", line 41, in <module>
    from comicapi.comicarchive import *
  File "C:\Users\Zack\Desktop\ComicStreamer-master\comicapi\comicarchive.py", line 12, in <module>
    from unrar import rarfile
  File "C:\Python27\lib\site-packages\unrar\rarfile.py", line 26, in <module>
    from unrar import unrarlib
  File "C:\Python27\lib\site-packages\unrar\unrarlib.py", line 45, in <module>
    unrarlib = ctypes.WinDLL(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found"

I was so sure it would run this time! Any ideas?

**Comment by ghost** [comment]
after the requirements you still have to install:

pip install image
pip install  sqlalchemy

i am trying it out on a virtual machine, but i am already 8 hours! in just
installing a visual studio c++ compiler

**Comment by LucidusAtra** [comment]
`pip install image` seemed to install something called django-1.10.4 and image-1.5.5
`pip install sqlalchemy` gave me a "requirement already satisfied" message.

`python comicstreamer` gives the same error message as before.

It's taken you 8 hours to install the c++ compiler? Wow!

**Comment by ghost** [comment]
i am not that fast,... i was downloading the sdk windows 10, and just found
the link to python and c++, which i wish i found that earlier... %^$ 8
hours its busy... my notebook fan is spinning like a turbine :-) and i
can't install the python c++ (if i need it) while the other is installing...

it probably missing the unrar.dll (which is in the package under
comicapi/...both the 64 bit and the 32 bit version)

https://github.com/Tristan79/ComicStreamer/tree/master/comicapi/UnRAR2/UnRARDLL

the copy the unrar.dll to the c:\windows\system32 folder

do not know how it works for the 64x dll one... i still have like 3 pixels
left installing...

**Comment by ghost** [comment]
dhshsh

**Comment by ghost** [comment]
ok, i copied the renamed 64bit filesUnRAR64.dll and UnRAR64.lib to

c:\python2.7\
c:\python2.7\DLLs
c:\Windows\System32\
c:\Windows\SysWOW64

one of them hit the sweet spot...

also removed the line

https://github.com/Tristan79/ComicStreamer/blob/master/comicstreamer#L4

and its running still not a package, but he! its something :-)

and did i mention the web is not finished :-)
