### ISSUE TITLE
cannot launch on windows

### ISSUE THREAD

**Issue by junknstuff** [beville/ComicStreamer#35]
Hi All,

I had ComicStreamer running for a few days on my Windows 7 Pro box but after I lost power yesterday, I haven't been able to get it back up. I deleted c:\ComicStreamer and re-cloned the repo but am receiving the following error. Any ideas what's up? I didn't get this error the first time around.

C:\Windows\system32>python c:\ComicStreamer\comicstreamer
Traceback (most recent call last):
  File "c:\ComicStreamer\comicstreamer", line 2, in <module>
    from comicstreamerlib.main import main
  File "c:\ComicStreamer\comicstreamerlib\main.py", line 35, in <module>
    from server import APIServer
  File "c:\ComicStreamer\comicstreamerlib\server.py", line 57, in <module>
    from database import *
  File "c:\ComicStreamer\comicstreamerlib\database.py", line 17, in <module>
    from sqlalchemy.ext.declarative import declarative_base
ImportError: No module named ext.declarative

**Comment by ghost** [comment]
Did you try wiping the db? It will not run when an old db is there.

**Comment by junknstuff** [comment]
hi @Tristan79 , what's the best way to do that? i have deleted the entire directory c:\ComicStreamer and cloned again from via Git hoping for a fresh start but it hasn't turned out that way.

Is the DB stored somewhere outside of c:\ComicStreamer? If so would you happen to know where?

**Comment by davide-romanini** [comment]
It seems you have not installed the required libraries. Did you tried `pip install -r requirements.txt`? I didn't tested it on windows, so there's a chance you'll need some more setup (a lot)..

**Comment by junknstuff** [comment]
@davide-romanini i downloaded the python dependencies and was able to run comicstreamer for about a day before the power went out and the server went down abruptly. no other changes were made to the server so i'm not sure why it wasn't able to come up with a simple python c:\ComicStreamer\comicstreamer

For reference, I am following this guide
http://www.htpcguides.com/install-comicstreamer-windows-for-personal-comic-server/
