### ISSUE TITLE
Trouble scanning files - No such file or directory

### ISSUE THREAD

**Issue by jbcpollak** [beville/ComicStreamer#39]
I just got comicstreamer running and it started its first scan. I saw this on the console:

```
2016-06-01 18:10:58,204 - INFO - Monitor: Removing missing or modified files from db (0 files)
2016-06-01 18:10:58,204 - INFO - Monitor: 442 new files to scan...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/boxen/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/boxen/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jpollak/src/ComicStreamer/comicstreamerlib/monitor.py", line 82, in mainLoop
    self.dofullScan(self.paths)
  File "/Users/jpollak/src/ComicStreamer/comicstreamerlib/monitor.py", line 264, in dofullScan
    md = self.getComicMetadata(filename)
  File "/Users/jpollak/src/ComicStreamer/comicstreamerlib/monitor.py", line 191, in getComicMetadata
    image_data = ca.getPage(0)
  File "/Users/jpollak/src/ComicStreamer/comicapi/comicarchive.py", line 769, in getPage
    image_data = self.archiver.readArchiveFile( filename )
  File "/Users/jpollak/src/ComicStreamer/comicapi/comicarchive.py", line 576, in readArchiveFile
    return subprocess.check_output(['mudraw', '-o','-', self.path, str(int(os.path.basename(page_num)[:-4]))])
  File "/opt/boxen/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/opt/boxen/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/boxen/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

In the logs I see:

```
2016-06-01 18:11:02,968 - DEBUG - 200 GET /scanstatus?api_key= (::1) 0.43ms
2016-06-01 18:11:01,962 - DEBUG - 200 GET /scanstatus?api_key= (::1) 0.42ms
2016-06-01 18:11:00,956 - DEBUG - 200 GET /scanstatus?api_key= (::1) 0.46ms
2016-06-01 18:10:59,949 - DEBUG - 200 GET /scanstatus?api_key= (::1) 0.82ms
2016-06-01 18:10:59,121 - DEBUG - Reading in 1 /Volumes/media/comics/Unknown/Pathfinder 07 (88)/Pathfinder 07 - Unknown.pdf
2016-06-01 18:10:58,941 - DEBUG - 200 GET /scanstatus?api_key= (::1) 0.58ms
2016-06-01 18:10:58,327 - DEBUG - Reading in 0 /Volumes/media/comics/Shannon Watters/Lumberjanes_ Issue One (2)/Lumberjanes_ Issue One - Shannon Watters.epub
2016-06-01 18:10:58,204 - INFO - Monitor: 442 new files to scan...
2016-06-01 18:10:58,204 - INFO - Monitor: Removing missing or modified files from db (0 files)
```

I did verify that last file does exist:

```
❯❯❯ ls /Volumes/media/comics/Unknown/Pathfinder\ 07\ \(88\)/Pathfinder\ 07\ -\ Unknown.pdf   ⏎
/Volumes/media/comics/Unknown/Pathfinder 07 (88)/Pathfinder 07 - Unknown.pdf
```

**Comment by jbcpollak** [comment]
this was because the `mudraw` application was not installed.

On my Mac, I was able to install it by doing the following:
- Install Homebrew (you probably already have it if you got this far already)
- Run `brew install mupdf-tools`
- Verify your homebrew install directory
- Run `sudo ln -s <path-to-homebrew>/bin/mutool <path-to-homebrew>/bin/mudraw`

**Comment by ghost** [comment]
https://github.com/Tristan79/ComicStreamer/tree/master/release

fixes a lot of pdf problems

**Comment by shelbeely** [comment]
anyone know how to solve this on linux? Ubuntu
