### ISSUE TITLE
Error starting davide-romanini's fork

### ISSUE THREAD

**Issue by pax0707** [beville/ComicStreamer#42]
Beville's works normally. 

```

E:\ComicStreamer2>python comicstreamer
Traceback (most recent call last):
  File "comicstreamer", line 6, in <module>
    from comicstreamerlib.main import main
  File "E:\ComicStreamer2\comicstreamerlib\main.py", line 35, in <module>
    from server import APIServer
  File "E:\ComicStreamer2\comicstreamerlib\server.py", line 57, in <module>
    from comicapi.comicarchive import *
  File "E:\ComicStreamer2\comicapi\comicarchive.py", line 32, in <module>
    from unrar import rarfile
  File "C:\Python27\lib\site-packages\unrar\rarfile.py", line 26, in <module>
    from unrar import unrarlib
  File "C:\Python27\lib\site-packages\unrar\unrarlib.py", line 45, in <module>
    unrarlib = ctypes.WinDLL(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

E:\ComicStreamer2>
```

**Comment by ghost** [comment]
You do not have an unrar library installed.

https://pypi.python.org/pypi/unrar/

**Comment by ghost** [comment]
http://www.rarlab.com/rar_add.htm

**Comment by ghost** [comment]
(if i am wrong than that probably means your python is ficked)....
_dlopen.... :/

**Comment by pax0707** [comment]
Already installed.
