### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by taibhse-designs** [beville/ComicStreamer#61]
I really want to use this along with chunky on the iPad Pro but is this project dead? Last update was 6 years ago?

**Comment by kounch** [comment]
You may try my fork. It is mainly focused on bringing it to Python3, and no binaries are provided:

https://github.com/kounch/ComicStreamer

**Comment by taibhse-designs** [comment]
> You may try my fork. It is mainly focused on bringing it to Python3, and no binaries are provided:
> 
> https://github.com/kounch/ComicStreamer

Oh I’ll give it a shot, is it still compatible with chunky and still actively maintained?

**Comment by kounch** [comment]
I use it on a raspberry pi with chunky every week. I think I have fixed almost all of the problems I have found.

**Comment by LETRA** [comment]
> You may try my fork. It is mainly focused on bringing it to Python3, and no binaries are provided:
> 
> https://github.com/kounch/ComicStreamer

@kounch Thank you for reviving the project. I'm trying to get it to work on a Thecus NAS with Debian Net Runner Core installed and it gives me this error message. All the dependencies are satisfied with pip3 also unrar. Any ideas?:

```
letra@Thecus-N2810:~/Aplicaciones/ComicStreamer-master$ ./comicstreamer
Traceback (most recent call last):
  File "./comicstreamer", line 6, in <module>
    from comicstreamerlib.main import main
  File "/home/letra/.local/share/Trash/files/ComicStreamer-master/comicstreamerlib/main.py", line 35, in <module>
    from server import APIServer
  File "/home/letra/.local/share/Trash/files/ComicStreamer-master/comicstreamerlib/server.py", line 57, in <module>
    from comicapi.comicarchive import *
  File "/home/letra/.local/share/Trash/files/ComicStreamer-master/comicapi/comicarchive.py", line 32, in <module>
    from unrar import rarfile
ImportError: No module named unrar
```

**Comment by kounch** [comment]
It seems that you didn't install libunrar with paver (see here: https://github.com/kounch/ComicStreamer/blob/master/README.md#manual-installation-linux-and-macos)

    python3 -m pip install -r requirements.txt
    python3 -m paver libunrar

**Comment by LETRA** [comment]
When I try to install libunrar the following error message appears:
```
letra@Thecus-N2810:~/Aplicaciones/ComicStreamer-master$ pip3 install paver libunrar
Requirement already satisfied: paver in /home/letra/.local/lib/python3.7/site-packages (1.2.4)
Collecting libunrar
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/libunrar/
```
The following command I can't execute without that library:

```
letra@Thecus-N2810:~/Aplicaciones/ComicStreamer-master$ python3 -m paver libunrar
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/letra/.local/lib/python3.7/site-packages/paver/__main__.py", line 2, in <module>
    paver.tasks.main()
  File "/home/letra/.local/lib/python3.7/site-packages/paver/tasks.py", line 878, in main
    _launch_pavement(args)
  File "/home/letra/.local/lib/python3.7/site-packages/paver/tasks.py", line 846, in _launch_pavement
    exec(compile(source, environment.pavement_file, 'exec'), mod.__dict__)
  File "pavement.py", line 20
    print "Fetching " + UNRAR_SRC + "..."        
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Fetching " + UNRAR_SRC + "...")?

```

**Comment by kounch** [comment]
I have just tried on a test environment following all the steps as listed on  
https://github.com/kounch/ComicStreamer/blob/master/README and it didn't fail.

Looking at your command line it doesn't look like you are inside a python3 venv. Did you follow all the steps in order?

**Comment by LETRA** [comment]
Before I found your fork I had installed the beville one. I'm going to see if I can clean up the whole previous installation I've done with python 2.7

**Comment by kounch** [comment]
You must use a clean venv and a clean directory with my fork. Mixing both may have unexpected results.

**Comment by LETRA** [comment]
I have done a clean installation and it is going well until I check that everything is correct. Then that calls for a module called PIL that I can't install:

```
letra@Thecus-N2810:~$ sudo /opt/comicstreamer/bin/python3 /opt/comicstreamer/master/comicstreamer --nobrowser --user-dir /opt/comicstreamer/.ComicStreamer
[sudo] password for letra: 
Traceback (most recent call last):
  File "/opt/comicstreamer/master/comicstreamer", line 11, in <module>
    from comicstreamerlib.main import main
  File "/opt/comicstreamer/master/comicstreamerlib/main.py", line 31, in <module>
    import comicstreamerlib.utils
  File "/opt/comicstreamer/master/comicstreamerlib/utils.py", line 31, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

```
letra@Thecus-N2810:~$ sudo pip3 install pil
ERROR: Could not find a version that satisfies the requirement pil (from versions: none)
ERROR: No matching distribution found for pil
```

**Comment by kounch** [comment]
PIL is part of module Pillow, which is in requirements.txt 

If `python3 -m pip install -r requirements.txt` runs well, and _inside the venv_, it has to be installed.

Again, looking at your command line, it looks like the pip3 install commands are not being done _after_ activating the venv. Could it be that you have made a venv, but then installed all the modules globally in your system?

Please check again that all the steps are done correctly, in the same order, and in the same session.

**Comment by LETRA** [comment]
Thank you for your answer. That could indeed have happened. I've tried to undo a new clean installation and the only flaw I have is that I can't start it up with the line 

> /opt/comicstreamer/bin/python3

python3 exists in the folder as symlink to /usr/bin/python3 but comicstreamer doesn't start if I include that route.

I don't know if this is a big problem that causes less security on the server or I can leave it at that. Otherwise your comicstreamer fork seems to be working fine, I just have a problem with the encoding of some Spanish titles:

![Captura de pantalla 2020-05-29 a las 4 36 34](https://user-images.githubusercontent.com/16805254/83215109-6fa45c00-a166-11ea-8b7d-8ecf443d1b49.jpg)

**Comment by kounch** [comment]
That's something to look into. If you tag your files with comictagger and rebuild the database, then the titles and other information will be shown correctly.

**Comment by LETRA** [comment]
I have reconfigured locales to es_ES.UTF-8 because I don't want to load the server too much, since the processor is not very strong and I have read that many tags can give failures in database. Then this error appears when I start the service, however if I launch the command from the terminal comicstreamer works without problems.

```
letra@Thecus-N2810:~$ sudo systemctl status comicstreamer
● comicstreamer.service - ComicStreamer Service
   Loaded: loaded (/etc/systemd/system/comicstreamer.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-05-29 17:24:51 CEST; 6s ago
  Process: 17173 ExecStart=/opt/comicstreamer/master/comicstreamer --nobrowser --user-dir /opt/comicstreamer/.ComicStreamer (code=exited, status=1/FAILURE)
 Main PID: 17173 (code=exited, status=1/FAILURE)

may 29 17:24:51 Thecus-N2810 comicstreamer[17173]:     Launcher().go()
may 29 17:24:51 Thecus-N2810 comicstreamer[17173]:   File "/opt/comicstreamer/master/comicstreamerlib/main.py", line 59, in go
may 29 17:24:51 Thecus-N2810 comicstreamer[17173]:     comicstreamerlib.utils.fix_output_encoding()
may 29 17:24:51 Thecus-N2810 comicstreamer[17173]:   File "/opt/comicstreamer/master/comicstreamerlib/utils.py", line 62, in fix_output_encoding
may 29 17:24:51 Thecus-N2810 comicstreamer[17173]:     locale.setlocale(locale.LC_ALL, "")
may 29 17:24:51 Thecus-N2810 comicstreamer[17173]:   File "/usr/lib/python3.7/locale.py", line 604, in setlocale
may 29 17:24:51 Thecus-N2810 comicstreamer[17173]:     return _setlocale(category, locale)
may 29 17:24:51 Thecus-N2810 comicstreamer[17173]: locale.Error: unsupported locale setting
may 29 17:24:51 Thecus-N2810 systemd[1]: comicstreamer.service: Main process exited, code=exited, status=1/FAILURE
may 29 17:24:51 Thecus-N2810 systemd[1]: comicstreamer.service: Failed with result 'exit-code'.

```

**Comment by LETRA** [comment]
Fixed adding "es_ES.UTF-8" to /usr/lib/python3.7/locale.py line 604
